# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SOSIexpressions
                                 A QGIS plugin
 Expressions related to 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-11-22
        copyright            : (C) 2023 by Morten Sickel
        email                : morten@sickel.net
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Morten Sickel'
__date__ = '2023-11-22'
__copyright__ = '(C) 2023 by Morten Sickel'


from qgis.PyQt.QtCore import QObject

from .functions import registerFunctions



# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Initiates SOSIexpressions class .
    This class has no UI, it is just adding in a new function.
    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    return SOSIexpressionsPlugin(iface)


class SOSIexpressionsPlugin(QObject):
    def __init__(self, iface):
        super().__init__()

    def initGui(self):
        registerFunctions()

    def unload(self):
        registerFunctions(False)

